language: java

jdk: 
  - oraclejdk8
  - openjdk11

addons:
  sonarcloud:
    organization: "quentinleroy62-github" # the key of the org you chose at step #3
    token:
      secure: 67364e8161a5316f71aff0b10cf658d8bd78fbb0 # encrypted value of your token

before install:
  - echo $TRAVIS_COMMIT
  - echo $TRAVIS_TAG
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_BUILD_NUMBER

#script:
  # other script steps might be done before running the actual analysis
  #- sonar-scanner
  #- docker build -t petclic:$TRAVIS_BUILD_NUMBER .

stages:
  - test
  - quality
  - deploy
jobs:
  include:
    - stage: quality
      script:
        - sonar-scanner
    - stage: deploy
      script:
        - curl https://cli-assets.heroku.com/install.sh | sh
        - heroku --version
        - heroku container:login
        - heroku container:push web --app petclini
        - heroku container:release web --app petclini

